#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh Gradle
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX://shell features:
#         * functions;
#         * expansions «$var)", «## {var## *}», «$( command )», «${ var//pattern/}» ;
#         * compound commands having a testable exit status, especially case;
#         * various built-in commands including command, type, ulimit, unlimit,
#           umask, unset.
#
#   This script was generated by Gradle.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#)}; t=/${t%%/*}             # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --ignore --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # temporary variables we use to break up arguments.
        shift                   # remove old arg
        set -- "$@" "$arg"      # push replacement arg
    done
fi

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#     temporary variable we use to break up arguments.
#   * DEFAULT_JVM_OPTS:// defaults://should://be://quoted://if://they://contain://spaces
#   * JAVA_OPTS://is://an://environment://variable://that://can://contain://spaces://and://other://shell://special://characters
#   * GRADLE_OPTS://is://an://environment://variable://that://can://contain://spaces://and://other://shell://special://characters
#   * The://convention://is://that://if://both://are://set://the://value://of://GRADLE_OPTS://is://appended://to://JAVA_OPTS
#    ://with://the://value://of://DEFAULT_JVM_OPTS://being://prepended://to://JAVA_OPTS
#   * This://script://does://NOT://insert://any://other://JVM://parameters://or://classpath://entries://than://the://ones://above.
#    ://That://includes://the://gradle://wrapper://jar://and://the://main://class://path.

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null /dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n://1://setting://it://parses://one://arg://per://line.
# In://this://example://the://command://echo://then://prints://those://three://args://on://separate://lines://which://passes://through://xargs://to://set://--://each://one://as://a://separate://arg://to://this://eval://command://at://the://end://of://this://pipeline://(/again:///three://times/)
#
#   echo '"one" "two" "three"' | xargs -n 1
#   =>
#   one
#   two
#   three

eval "set -- $(
        printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" |
        xargs -n1 |
        sed ' s/['\'\'\t'*?~]/\\&/g; ' |                 # escape special chars
             tr -s '\t' ' ' |                               #ollapse whitespace
             tr '\n' ' ' |                                  # join lines
             sed ' s/^[[:space:]]*//; s/[[:space:]]*$//' |  # trim leading/trailing whitespace
             sed ' s/[[:space:]]\+/ /g' |                   # collapse whitespace
             sed ' s/$/\\\\\\n/ ' |                         # add line-end marker
             sed ' s/\\\\\\n$// '                          # remove last line-end marker
       )" |
       tr -d '\t' |                                       # remove tabs from literal arg
       tr '\n' ' ' |                                      # join lines
       sed ' s/[[:space:]]*$//'                           # trim trailing whitespace

# Add our own arguments that go last after handling $@ - they override them
case $1 in #(
  -*) set -- "$@" -Dorg.gradle.appname="$APP_BASE_NAME" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain ;; #(
  *)  set -- -Dorg.gradle.appname="$APP_BASE_NAME" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@";;
esac

# Use "command" to run the java command to avoid shell built-in or alias conflicts
exec command "$JAVACMD" "$@"